name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: apt-get install libasound2-dev
      run: sudo apt-get install libasound2-dev -y

    - name: mkdir build
      run: mkdir build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLABSOUND_ASOUND=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v2
      with:
        name: linux-amd64
        path: ${{github.workspace}}/build/libLabSoundBridge.so

  build-windows-amd64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: mkdir build
      run: mkdir build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v2
      with:
        name: windows-amd64
        path: ${{github.workspace}}/build/Release/LabSoundBridge.dll

  android:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        abi: ['armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
    
    - name: mkdir build
      run: mkdir build

    - name: Build ${{ matrix.abi }}
      run: cmake -B ${{github.workspace}}/build -DANDROID_ABI=$ANDROID_ABI -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DANDROID_PLATFORM=android-16 -DANDROID_NDK=$ANDROID_NDK_HOME -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_TOOLCHAIN=clang -DCMAKE_SYSTEM_NAME=Android -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=${{github.workspace}}/lib/$ANDROID_ABI/ && cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        ANDROID_ABI: ${{ matrix.abi }}

    - uses: actions/upload-artifact@v2
      with:
        name: android-${{ matrix.abi }}
        path: ${{github.workspace}}/lib

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: mkdir build
      run: mkdir build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: mv
      run: mkdir build/lib && mv build/LabSoundBridge.framework build/lib/LabSoundBridge.framework

    - name: Codesign executable
      env: 
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      run: |
        rm -f build.keychain
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        security create-keychain -p abc123 build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p abc123 build.keychain
        security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k abc123 build.keychain
        codesignIdentity=`security find-identity -p codesigning -v | grep -Eo "[0-9A-F]{40}" | head -n 1`
        /usr/bin/codesign --force -s $codesignIdentity ${{github.workspace}}/build/lib/LabSoundBridge.framework -v

    - uses: actions/upload-artifact@v2
      with:
        name: macos
        path: ${{github.workspace}}/build/lib

